service: logoSwitch

provider:
    name: aws
    runtime: nodejs12.x
    memorySize: 512
    timeout: 10
    versionFunctions: false
    region: eu-north-1
    iamRoleStatements:
        - Effect: Allow
          Action:
              - s3:PutObject
          Resource: "arn:aws:s3:::static.wallsin.com/*"

#resources:
    #Resources:
        #staticBucket:
            #Type: AWS::S3::Bucket
            #Properties:
                #BucketName: static.wallsin.com
                #WebsiteConfiguration:
                    #IndexDocument: index.html
        #staticBucketPolicy:
            #Type: AWS::S3::BucketPolicy
            #Properties:
                #Bucket: static.wallsin.com
                #PolicyDocument: {
                    #Statement: [
                        #{
                            #Sid: PublicReadGetObject,
                            #Effect: Allow,
                            #Principal: '*',
                            #Action: s3:GetObject,
                            #Resource: arn:aws:s3:::static.wallsin.com/*
                        #}
                    #]
                #}

package:
    exclude:
        - wercker.yml
        - Dockerfile
        - dev-docker.sh

functions:
    logo-switch:
        handler: handler.logoSwitch
        name: LogoSwitch
        description: Uploads new version of logo.
        events:
            - schedule: cron(0 23 * * ? *)
